---
 - hosts: ubuntu
   become: yes
   tasks:
     - name: install docker.io
       apt:
         name: docker.io
         state: present 

     - name: pull docker image
       shell:  sudo docker pull komal921

     - name: run docker image
       shell: sudo docker run -itd komal921

